KudWafter OSD
project-anni/repo pull request #41
Opened 2021-09-23 07:22 UTC by SeraphJACK

2021-09-23 14:24 UTC, SeraphJACK commented on album/KSLA-0174~5.toml
> +artist = "[Unknown Artist]"
TODO

2021-09-26 04:41 UTC, Yesterday17 requested changes
- [ ] Missing category file
- [ ] #16 related KudWafter Discs
  - [ ] [KSLA-0057]『クドわふたー Original SoundTrack』
  - [ ] [KSLA-0066]『クドわふたーアレンジアルバム Albina ~Assorted kudwaf Songs~』
  - [ ] [KSLA-0077]『Kud Wafter Original Sound Track』
  - [ ] [KSLA-0089]『リトルバスターズ！／クドわふたー Piano Arrange Album '''ripresa'''』

2021-09-26 04:41 UTC, Yesterday17 commented on album/KSLA-0174~5.toml
> +artist = "[Unknown Artist]"
Various Artists

2021-09-26 04:41 UTC, Yesterday17 commented on album/KSLA-0174~5.toml
> +type = "normal"
Unnecessary `normal` type for tracks(disc type implies normal).

2021-09-26 04:41 UTC, Yesterday17 commented on album/KSLA-0174~5.toml
> +type = "normal"
~~normal~~

2021-09-26 04:41 UTC, Yesterday17 commented on album/KSLA-0174~5.toml
> +type = "normal"
~~normal~~(Why track type of this artist is normal?)

2021-09-26 04:41 UTC, Yesterday17 commented on album/KSLA-0174~5.toml
> +type = "normal"
~~normal~~ (Artist)

2021-09-26 04:41 UTC, Yesterday17 commented on album/KSLA-0174~5.toml
> +
~~New line~~

2021-09-26 04:41 UTC, Yesterday17 commented on album/KSLA-0174~5.toml
> +type = "normal"
~~normal~~

2021-09-26 04:41 UTC, Yesterday17 commented on album/KSLA-0174~5.toml
> +type = "normal"
~~normal~~

2021-09-26 04:41 UTC, Yesterday17 commented on album/KSLA-0174~5.toml
> +type = "normal"
~~normal~~

2021-09-29 12:59 UTC, Yesterday17 approved these changes

2021-09-29 12:59 UTC, merged